
# This file was generated by 'versioneer.py' (0.16+dev) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": "no suitable tags",
 "full-revisionid": "5e430b683aecd3bae6c46d21b1c005981291db24",
 "version": "0+unknown"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
